project_name: goblade

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - &main_build
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64

    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser

  - <<: *main_build
    id: goblade-packed
    binary: goblade-packed
    hooks:
      post: upx --best {{ .Path }}

archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
