project_name: goblade

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - &main_build
    env:
      - CGO_ENABLED=1
    targets:
      - windows_amd64_v1

    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/sparta142/goblade/cmd.version={{ .Version }}
      - -X github.com/sparta142/goblade/cmd.gitSummary={{ .Summary }}
      - -X github.com/sparta142/goblade/cmd.commitDate={{ .CommitDate }}
      - -X github.com/sparta142/goblade/cmd.builtBy=goreleaser

  - <<: *main_build
    id: goblade-packed
    binary: goblade-packed
    hooks:
      post:
        - upx --best {{ .Path }}

archives:
  - format: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
