name: Code scanning

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "28 4 * * 5"

permissions:
  contents: read

env:
  CGO_ENABLED: 1

jobs:
  codeql:
    name: CodeQL

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version-file: go.mod
          cache: true

      - name: Install libpcap
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y libpcap-dev

      - name: Initialize CodeQL
        uses: github/codeql-action/init@c3b6fce4ee2ca25bc1066aa3bf73962fda0e8898
        with:
          languages: go

      - name: Build
        run: go build .

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@c3b6fce4ee2ca25bc1066aa3bf73962fda0e8898
        with:
          category: "/language:go"

  scorecard:
    name: OSSF Scorecards

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: Upload results
        uses: github/codeql-action/upload-sarif@c3b6fce4ee2ca25bc1066aa3bf73962fda0e8898
        with:
          sarif_file: results.sarif
