name: Code scanning

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "28 4 * * 5"

permissions: read-all

jobs:
  codeql:
    name: CodeQL

    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 1

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version-file: go.mod
          cache: true

      - name: Install libpcap
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y libpcap-dev

      - name: Initialize CodeQL
        uses: github/codeql-action/init@17573ee1cc1b9d061760f3a006fc4aac4f944fd5
        with:
          languages: go

      - name: Build
        run: |
          go generate ./...
          go build .

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@17573ee1cc1b9d061760f3a006fc4aac4f944fd5
        with:
          category: "/language:go"

  scorecard:
    name: OSSF Scorecards

    runs-on: ubuntu-latest

    permissions:
      security-events: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: Upload results
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5
        with:
          sarif_file: results.sarif

  sonarcloud:
    name: SonarCloud

    runs-on: windows-latest

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_out
      CGO_ENABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version-file: go.mod
          cache: false # build-wrapper doesn't detect cgo files with this enabled

      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@f218be71ddd704dcf7f1b761caa6ffb14134094a

      - name: Generate files
        run: go generate ./...

      - name: Run build-wrapper
        run: >-
          build-wrapper-win-x86-64
          --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }}
          go build .

      - name: Run sonar-scanner
        run: >-
          sonar-scanner
          --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
          --define sonar.cfamily.cache.enabled=false
          --define sonar.projectKey=Sparta142_goblade
          --define sonar.organization=sparta142
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
