name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CGO_ENABLED: 1

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Install libpcap
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y libpcap-dev

      - name: Test
        run: go test -v ./...

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Install libpcap
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y libpcap-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
