name: Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CGO_ENABLED: 1

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version-file: go.mod
          cache: true

      - name: Install libpcap
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y libpcap-dev

      - name: Test
        run: go test -v ./...

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version-file: go.mod

      - name: Install libpcap
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y libpcap-dev

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376
        with:
          version: v1.50
